### ISSUE TITLE
Unimplemented Regions

### ISSUE THREAD

**Issue by ActualAnthonino** [ThePurityOfChaos/SkyblockImprovements#11]
Regions: "The Forge","Forge Basin","Far Reserve","Goblin Burrows","Great Ice Wall","Divan's Gateway","The Mist","Royal Mines","Cliffside Veins","C&C Minecarts Co.","Dwarven Base Camp","Glacite Tunnels","Glacite Mineshafts"

Areas: "Mineshaft"

**Comment by ThePurityOfChaos** [comment]
Added
