### ISSUE TITLE
PackSwapper Displaying A Player's Level & Prefix

### ISSUE THREAD

**Issue by ActualAnthonino** [ThePurityOfChaos/SkyblockImprovements#7]
![image](https://github.com/ThePurityOfChaos/SkyblockImprovements/assets/166943250/27c55a55-5709-4c85-bcc5-41809e962ccd)

**Comment by ActualAnthonino** [comment]
Unsure what caused this, let alone where this data was pulled from; I couldn't see a lvl 213 in my lobby while I had this.
Swapping lobbies fixed this. Have yet to reencounter.

**Comment by ThePurityOfChaos** [comment]
Figured this one out, it was pulling the Scoreboard's data _including the parts of the scoreboard which were not displayed_. Fixed in version 0.1.2, by limiting it exclusively to the sidebar.
