### ISSUE TITLE
Item Pickup Log not disappearing

### ISSUE THREAD

**Issue by ActualAnthonino** [ThePurityOfChaos/SkyblockImprovements#9]
![image](https://github.com/ThePurityOfChaos/SkyblockImprovements/assets/166943250/d023e59c-64f1-43b6-a8bc-0d08d3550a34)

Unsure what I did to cause this; was testing out the settings for SetDuration and SetDistance and it just got stuck like this seemingly instantly.

**Comment by ThePurityOfChaos** [comment]
Could you please try to reproduce the bug?
This might be intentional if you set the duration high enough.

**Comment by ActualAnthonino** [comment]
Small issue with that... _it hasn't exactly fixed itself..._

I've just found out the bug persists across game sessions; even if you close the game and reopen it, once an item is logged, **it doesn't go away.** I can't reproduce the bug because it's still yet to even disappear. I've tried setting the duration to something absurdly high then absurdly low, setting the colorcode, setting the distance - _nothing changes it._

Apologies for not informing you about this earlier; _I turned the pickup log off when I first discovered this and forgot to turn it back on like a dillweed._

**Comment by ThePurityOfChaos** [comment]
Could you send in your IPLconfig.json file in the config->sbimp folder?

**Comment by ActualAnthonino** [comment]
_Howu I do dat?_

**Comment by ThePurityOfChaos** [comment]
You previously placed the mod in your Mods folder; config is in the same area. If you go to your Mods folder and go back once, you'll see a folder called config. Then, find "IPLconfig.json" in that folder, open it in Notepad, and copy-paste that in here.

**Comment by ActualAnthonino** [comment]
{
  "button": [
    510,
    302,
    128,
    32
  ],
  "advanced": {
    "duration": 5000,
    "distance": 9,
    "colorCode": "f",
    "showSacks": true
  },
  "enabled": false
}

Not a DAMN clue how duration got set to **5000**; I never even typed that in.

**Comment by ThePurityOfChaos** [comment]
that was a failed conversion from seconds to milliseconds most likely; it should work if you change it in the newer versions
